version: '3'

services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    command: '-jar DynamoDBLocal.jar -sharedDb -inMemory'
    container_name: dynamodb-local
    ports:
      - 8000:8000
    working_dir: /home/dynamodblocal
  app:
    build:
      context: .
    depends_on:
      - dynamodb
    working_dir: /home/app
    volumes:
      - ./dist:/home/app/dist
    environment:
      DYNAMODB_ENDPOINT_URL: http://dynamodb:8000
